spring.application.name=ReactiveStreamRestAppCRUD

spring.r2dbc.url=r2dbc:mysql://localhost:3306/bookdb
spring.r2dbc.username=root
spring.r2dbc.password=root

logging.level.org.springframework.r2dbc=DEBUG

